/*
 * Copyright © Thinking Robots, Inc., Tufts University, and others 2024.
 */
package edu.tufts.hrilab.ros2.ros2jrosclient.messages;

import id.jrosmessages.MessageMetadata;
import id.jrosmessages.RosInterfaceType;
import id.xfunction.XJson;
import java.util.Objects;
import pinorobotics.jros2actionlib.actionlib_msgs.Action2GoalIdMessage;
import pinorobotics.jros2actionlib.actionlib_msgs.Action2GoalMessage;

/**
 * Definition for test_server/FibonacciActionGoal ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION
 * DEFINITION ======
 */
@MessageMetadata(name = FibonacciActionGoalMessage.NAME, interfaceType = RosInterfaceType.ACTION)
public class FibonacciActionGoalMessage implements Action2GoalMessage<FibonacciGoalMessage> {

    static final String NAME = "action_tutorials_interfaces/FibonacciActionGoal";

    public Action2GoalIdMessage goal_id;

    public FibonacciGoalMessage goal;

    @Override
    public FibonacciActionGoalMessage withGoalId(Action2GoalIdMessage goal_id) {
        this.goal_id = goal_id;
        return this;
    }

    @Override
    public FibonacciActionGoalMessage withGoal(FibonacciGoalMessage goal) {
        this.goal = goal;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(goal_id, goal);
    }

    @Override
    public boolean equals(Object obj) {
        var other = (FibonacciActionGoalMessage) obj;
        return Objects.equals(goal_id, other.goal_id) && Objects.equals(goal, other.goal);
    }

    @Override
    public String toString() {
        return XJson.asString(
                "goal_id", goal_id,
                "goal", goal);
    }
}
