/*
 * Copyright © Thinking Robots, Inc., Tufts University, and others 2024.
 */

/**
 * @author luca
 */
package edu.tufts.hrilab.action.gui;

import javax.swing.*;
import java.awt.*;

/**
 * A ScriptEditorTab is the component that sits in the tab bar of the JTabbedPane.
 * It adds a close button to the standard tab.
 */
public class ScriptEditorTab {
  private JButton closeButton;
  private JLabel title;
  private JPanel tabPanel;

  public ScriptEditorTab(DatabaseViewer gui, JTabbedPane editor, String name, String id) {
    title.setText(name);
    closeButton.setIcon(UIManager.getIcon("InternalFrame.closeIcon"));
    closeButton.addActionListener(e -> {
      int index = editor.indexOfTab(id);
      if (index >= 0) {
        editor.removeTabAt(index);
        gui.removedTab(id); // Notify GUI that we're closing this tab.
      }
    });
  }

  public void setName(String name) {
    title.setText(name);
  }

  public JPanel getPanel() {
    return tabPanel;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    tabPanel = new JPanel();
    tabPanel.setLayout(new GridBagLayout());
    tabPanel.setOpaque(false);
    title = new JLabel();
    title.setText("title");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.weightx = 1.0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.WEST;
    tabPanel.add(title, gbc);
    closeButton = new JButton();
    closeButton.setAlignmentY(0.0f);
    closeButton.setBorderPainted(false);
    closeButton.setContentAreaFilled(true);
    closeButton.setEnabled(true);
    closeButton.setIconTextGap(0);
    closeButton.setMargin(new Insets(0, 0, 0, 0));
    closeButton.setOpaque(false);
    closeButton.setText("");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.weighty = 1.0;
    gbc.anchor = GridBagConstraints.EAST;
    tabPanel.add(closeButton, gbc);
  }

  public JComponent $$$getRootComponent$$$() {
    return tabPanel;
  }
}
