free(fetch).
actorAt(fetch,movebaselocation_6).

areaBoundToLocation(tableA, movebaselocation_0).
areaBoundToLocation(tableB, movebaselocation_1).
areaBoundToLocation(tableC, movebaselocation_2).
areaBoundToLocation(tableD, movebaselocation_3).
areaBoundToLocation(tableE, movebaselocation_4).
areaBoundToLocation(tableF, movebaselocation_5).
areaBoundToLocation(tableG, movebaselocation_6).

%TODO: autogenerated via consultant, etc. PDDLGenerator? and/or observer on the consultant?
accessibleBy(fetch,movebaselocation_0).
accessibleBy(fetch,movebaselocation_1).
accessibleBy(fetch,movebaselocation_2).
accessibleBy(fetch,movebaselocation_3).
accessibleBy(fetch,movebaselocation_4).
accessibleBy(fetch,movebaselocation_5).
accessibleBy(fetch,movebaselocation_6).
accessibleBy(fetch,movebaselocation_7).

actorInRoom(fetch,room1).

%TODO: should be provided in consultant?
locationInRoom(movebaselocation_0, room1).
locationInRoom(movebaselocation_1, room1).
locationInRoom(movebaselocation_2, room1).
locationInRoom(movebaselocation_3, room1).
locationInRoom(movebaselocation_4, room1).
locationInRoom(movebaselocation_5, room1).
locationInRoom(movebaselocation_6, room1).
locationInRoom(movebaselocation_7, room1).
