% Hard-coded facts for testing proof-of-concept kit-assembly-only planning domain
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5

%TODO: make these assertions in the setup script?
free(temi).
actorAt(temi,temilocation_1).

%TODO: autogenerated via consultant, etc. PDDLGenerator? and/or observer on the consultant?
accessibleBy(temi, temilocation_2). %% gamma
accessibleBy(temi, temilocation_1). %% alpha
accessibleBy(temi, temilocation_0). %% completedAssemblyLocation

actorInRoom(temi,room1).

%TODO: should be provided in consultant?
locationInRoom(temilocation_1, room1).
locationInRoom(temilocation_2, room1).
locationInRoom(temilocation_0, room2).

%TODO: this is related to KR for relationships between locations across consultants. where does it come from?
adjacent(movebaselocation_7, temilocation_2). %%todo: these locations should probably have different kbnames, since the temi is going to be involved!!!!
