% Hard-coded facts for testing proof-of-concept kit-assembly-only planning domain
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5

%TODO:brad: should this live in multiRobotCaddy.pl? Will we ever be able to auto generate it?
function(amount, location, property).
predicate(propertyof,var,property).

%TODO: make these assertions in the setup script?
free(self).
at(self,movebaselocation_0).
%TODO: autogenerated via consultant, etc. PDDLGenerator? and/or observer on the consultant?
accessibleBy(self,movebaselocation_0).
accessibleBy(self,movebaselocation_1).
accessibleBy(self,movebaselocation_2).
accessibleBy(self,movebaselocation_3).
accessibleBy(self,movebaselocation_4).
accessibleBy(self,movebaselocation_5).
accessibleBy(self,movebaselocation_6).
accessibleBy(self,movebaselocation_7).

%properties that appear in the consultant, but aren't used in conditions or effects
object(gearboxbottomlocation,property).
object(dropofflocation,property).
object(screwlocation,property).
object(smallgearlocation,property).
object(largegearlocation,property).
object(gearboxtoplocation,property).
object(caddylocation,property).
