(define(problem s0-problem)
(:domain s0)
(:objects base - object in_missile_fire_range - object missile - object friendly_plane - object hostile_plane - object )
(:init
	(route base in_missile_fire_range)
	(route in_missile_fire_range base)
	(is_friendly_plane friendly_plane)
	(is_hostile_plane hostile_plane)
	(is_missile missile)
	(at friendly_plane base)
	(at hostile_plane in_missile_fire_range)
	(have friendly_plane missile)
	(is_out_of_hostile_range friendly_plane)
	(we_are_alive)
)
(:goal (and  (dead hostile_plane)  (at friendly_plane base) ))
)
